title: Not a blog but personal notes.
description:
author: Vincent Bouchet
github: https://github.com/vbouchet31
about: I am a Drupal architect, runner and traveler.
avatar_url: /static/img/avatar.png

enableTags: false
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/vbouchet31"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/vbouchet"
    - icon: fa-github
      link: "https://github.com/vbouchet31"
    - icon: fa-strava
      link: "https://www.strava.com/athletes/6922811"

share:
  twitter_username: vbouchet31

urls:
    - text: About Me
      url: /about/
    - text: Raspberry
      url: /category/respberry
    - text: XML Feed
      url: /feed.xml

url: "https://vbouchet31.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
